version: "3.8"

services:
  build:
    context: .
    container_name: { env.repo_name }
    name: { env.repo_name }
    dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped
